/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.manurul.view.modal;

import com.manurul.lib.InputBorder;
import java.awt.Toolkit;
import com.manurul.lib.RoundedPanel;
import com.manurul.model.JurusanModel;
import com.manurul.model.LogModel;
import com.manurul.view.Dashboard;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author caesarhome
 */
public class JurusanUSER extends javax.swing.JFrame {

    /**
     * Creates new form JurusanUSER
     */
    private String title = "Edit";
    
    private String action;
    private String kode;
    private String nama;
    
    private ImageIcon successIcon;
    
    public JurusanUSER(String Action, String Kode) {
        initComponents();
        
        // INIT GLOBAL VARIBLE
        this.action = Action;
        this.kode = Kode;
        
        // SET SIZE
        this.setSize(1024, 345);
        
        // SET CENTER LOCATION
        this.setLocationRelativeTo(null);
        
        // SET DISABLE RESIZESABLE
        this.setResizable(false);
        
        // SET ICON
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../../src/LOGO_MANURUL.png")));
        
        // INIT INPUT BORDER PADDING
        InputBorder.set(INPUT_KODE_JUR, 8);
        InputBorder.set(INPUT_NAMA_JUR, 8);
        InputBorder.set(INPUT_LAST_UPDATE_JUR, 8);
        InputBorder.set(INPUT_CREATED_JUR, 8);
        
        // SET COMPONENT BASED ON ACTION
        if(Action.equals("ADD")){
            
            this.title = "Tambah";
            
            this.setSize(1024, 285);
            
            LABEL_LAST_UPDATE_JUR.setVisible(false);
            INPUT_LAST_UPDATE_JUR.setVisible(false);
            LABEL_LAST_CREATED_JUR.setVisible(false);
            INPUT_CREATED_JUR.setVisible(false);
            
            BTN_HAPUS_JUR.setVisible(false);
        
        }else{
            JurusanModel JM = new JurusanModel();
            JM.getSelected(Kode);
            kode = JM.getKode();
            nama = JM.getNama();
        }
        
        // SET TITLE
        this.setTitle("MA Nurul Islam Library Management - " + this.title + " Jurusan");
        
        // SET SUCCESS ICON
        ImageIcon successIcon = new ImageIcon(getClass().getResource("/com/manurul/src/ICON_SUCCESS.png"));
        this.successIcon = successIcon;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MAIN_FRAME = new javax.swing.JPanel();
        CONTAINER = new RoundedPanel(15, Color.WHITE);
        INPUT_KODE_JUR = new javax.swing.JTextField();
        LABEL_KODE_JUR = new javax.swing.JLabel();
        INPUT_NAMA_JUR = new javax.swing.JTextField();
        LABEL_NAMA_JUR = new javax.swing.JLabel();
        LABEL_LAST_UPDATE_JUR = new javax.swing.JLabel();
        INPUT_LAST_UPDATE_JUR = new javax.swing.JTextField();
        INPUT_CREATED_JUR = new javax.swing.JTextField();
        LABEL_LAST_CREATED_JUR = new javax.swing.JLabel();
        BTN_HAPUS_JUR = new javax.swing.JButton();
        BTN_SIMPAN_JUR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);

        MAIN_FRAME.setBackground(new java.awt.Color(239, 240, 245));

        CONTAINER.setBackground(new java.awt.Color(239, 240, 245));

        INPUT_KODE_JUR.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_KODE_JUR.setForeground(new java.awt.Color(96, 96, 96));
        INPUT_KODE_JUR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));
        INPUT_KODE_JUR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                INPUT_KODE_JURKeyPressed(evt);
            }
        });

        LABEL_KODE_JUR.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_KODE_JUR.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_KODE_JUR.setText("Kode Jurusan");

        INPUT_NAMA_JUR.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_NAMA_JUR.setForeground(new java.awt.Color(96, 96, 96));
        INPUT_NAMA_JUR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));
        INPUT_NAMA_JUR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                INPUT_NAMA_JURKeyPressed(evt);
            }
        });

        LABEL_NAMA_JUR.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_NAMA_JUR.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_NAMA_JUR.setText("Nama Jurusan");

        LABEL_LAST_UPDATE_JUR.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_LAST_UPDATE_JUR.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_LAST_UPDATE_JUR.setText("Terakhir Diperbarui");

        INPUT_LAST_UPDATE_JUR.setEditable(false);
        INPUT_LAST_UPDATE_JUR.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_LAST_UPDATE_JUR.setForeground(new java.awt.Color(96, 96, 96));
        INPUT_LAST_UPDATE_JUR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));

        INPUT_CREATED_JUR.setEditable(false);
        INPUT_CREATED_JUR.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_CREATED_JUR.setForeground(new java.awt.Color(96, 96, 96));
        INPUT_CREATED_JUR.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));

        LABEL_LAST_CREATED_JUR.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_LAST_CREATED_JUR.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_LAST_CREATED_JUR.setText("Tanggal Dibuat");

        javax.swing.GroupLayout CONTAINERLayout = new javax.swing.GroupLayout(CONTAINER);
        CONTAINER.setLayout(CONTAINERLayout);
        CONTAINERLayout.setHorizontalGroup(
            CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONTAINERLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(INPUT_KODE_JUR, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LABEL_KODE_JUR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_NAMA_JUR)
                    .addComponent(LABEL_NAMA_JUR, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_LAST_UPDATE_JUR)
                    .addComponent(LABEL_LAST_UPDATE_JUR, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(INPUT_CREATED_JUR)
                    .addComponent(LABEL_LAST_CREATED_JUR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        CONTAINERLayout.setVerticalGroup(
            CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONTAINERLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABEL_KODE_JUR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABEL_NAMA_JUR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABEL_LAST_UPDATE_JUR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INPUT_KODE_JUR, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(INPUT_LAST_UPDATE_JUR, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(INPUT_NAMA_JUR, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(LABEL_LAST_CREATED_JUR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_CREATED_JUR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        BTN_HAPUS_JUR.setBackground(new java.awt.Color(153, 153, 153));
        BTN_HAPUS_JUR.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        BTN_HAPUS_JUR.setForeground(new java.awt.Color(255, 255, 255));
        BTN_HAPUS_JUR.setText("Hapus");
        BTN_HAPUS_JUR.setBorder(null);
        BTN_HAPUS_JUR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_HAPUS_JURMouseClicked(evt);
            }
        });

        BTN_SIMPAN_JUR.setBackground(new java.awt.Color(0, 171, 60));
        BTN_SIMPAN_JUR.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        BTN_SIMPAN_JUR.setForeground(new java.awt.Color(255, 255, 255));
        BTN_SIMPAN_JUR.setText("Simpan");
        BTN_SIMPAN_JUR.setBorder(null);
        BTN_SIMPAN_JUR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_SIMPAN_JURMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MAIN_FRAMELayout = new javax.swing.GroupLayout(MAIN_FRAME);
        MAIN_FRAME.setLayout(MAIN_FRAMELayout);
        MAIN_FRAMELayout.setHorizontalGroup(
            MAIN_FRAMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MAIN_FRAMELayout.createSequentialGroup()
                .addGroup(MAIN_FRAMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MAIN_FRAMELayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(CONTAINER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MAIN_FRAMELayout.createSequentialGroup()
                        .addContainerGap(420, Short.MAX_VALUE)
                        .addComponent(BTN_HAPUS_JUR, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_SIMPAN_JUR, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        MAIN_FRAMELayout.setVerticalGroup(
            MAIN_FRAMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAIN_FRAMELayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(CONTAINER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(MAIN_FRAMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_SIMPAN_JUR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_HAPUS_JUR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_FRAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_FRAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean cekValidasi(String Action){
        
        try{
            
            // apakah input kosong ?
            if(INPUT_KODE_JUR.getText().equals("") || INPUT_NAMA_JUR.getText().equals("")){
                throw new Exception("Nilai input harus terisi!");
            }
            
            if(!Action.equals("DELETE")){
                // apakah input sama dengan data lama
                if(INPUT_KODE_JUR.getText().equals(kode) && INPUT_NAMA_JUR.getText().equals(nama)){
                    throw new Exception("Tidak ada perubahan data!");
                }
            }

            return true;
        
        }catch(Exception error){
            JOptionPane.showMessageDialog(null, error.getMessage(), "Terjadi Kesalahan!", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
    
    }
    
    private void simpan(){
        
        if(cekValidasi("INSERT")){
            JurusanModel JM = new JurusanModel();

            JM.setKode(INPUT_KODE_JUR.getText());
            JM.setNama(INPUT_NAMA_JUR.getText());

            if(JM.insertData()){
                JOptionPane.showMessageDialog(null, JM.getMessage(), "Sukses!", JOptionPane.INFORMATION_MESSAGE, this.successIcon);
                new LogModel().Action("TAMBAH JURUSAN", "Menambahkan jurusan "+INPUT_NAMA_JUR.getText(), Dashboard.nama_user);
                JM.getDataTable("");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, JM.getMessage(), "Terjadi Kesalahan!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
    private void update(){
        
        if(cekValidasi("UPDATE")){
            JurusanModel JM = new JurusanModel();
        
            JM.setKode(INPUT_KODE_JUR.getText());
            JM.setNama(INPUT_NAMA_JUR.getText());

            if(JM.updateData(kode)){
                JOptionPane.showMessageDialog(null, JM.getMessage(), "Sukses!", JOptionPane.INFORMATION_MESSAGE, this.successIcon);
                new LogModel().Action("UPDATE JURUSAN", "Memperbarui jurusan "+INPUT_NAMA_JUR.getText(), Dashboard.nama_user);
                JM.getDataTable("");
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, JM.getMessage(), "Terjadi Kesalahan!", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }
    
    private void BTN_SIMPAN_JURMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_SIMPAN_JURMouseClicked
        if(this.action.equals("ADD")){
            simpan();
        }else{
            update();
        }
    }//GEN-LAST:event_BTN_SIMPAN_JURMouseClicked

    private void BTN_HAPUS_JURMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_HAPUS_JURMouseClicked
        
        INPUT_KODE_JUR.setText(kode);
        INPUT_NAMA_JUR.setText(nama);
        
        // apakah input kosong ?
        if(cekValidasi("DELETE")){
            int hapus = JOptionPane.showConfirmDialog(null, "Benarkan anda ingin mengapus jurusan "+kode+" ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if(hapus == 0){
                JurusanModel JM = new JurusanModel();

                JM.setKode(kode);

                if(JM.deleteData()){
                    JOptionPane.showMessageDialog(null, JM.getMessage(), "Sukses!", JOptionPane.INFORMATION_MESSAGE, this.successIcon);
                    new LogModel().Action("HAPUS JURUSAN", "Menghapus jurusan "+INPUT_NAMA_JUR.getText(), Dashboard.nama_user);
                    JM.getDataTable("");
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, JM.getMessage(), "Terjadi Kesalahan!", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
        
    }//GEN-LAST:event_BTN_HAPUS_JURMouseClicked

    private void INPUT_KODE_JURKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_INPUT_KODE_JURKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            if(this.action.equals("ADD")){
                simpan();
            }else{
                update();
            }
        }
    }//GEN-LAST:event_INPUT_KODE_JURKeyPressed

    private void INPUT_NAMA_JURKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_INPUT_NAMA_JURKeyPressed
       if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            if(this.action.equals("ADD")){
                simpan();
            }else{
                update();
            }
        }
    }//GEN-LAST:event_INPUT_NAMA_JURKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JurusanUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JurusanUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JurusanUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JurusanUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JurusanUSER("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_HAPUS_JUR;
    private javax.swing.JButton BTN_SIMPAN_JUR;
    private javax.swing.JPanel CONTAINER;
    public static javax.swing.JTextField INPUT_CREATED_JUR;
    public static javax.swing.JTextField INPUT_KODE_JUR;
    public static javax.swing.JTextField INPUT_LAST_UPDATE_JUR;
    public static javax.swing.JTextField INPUT_NAMA_JUR;
    private javax.swing.JLabel LABEL_KODE_JUR;
    private javax.swing.JLabel LABEL_LAST_CREATED_JUR;
    private javax.swing.JLabel LABEL_LAST_UPDATE_JUR;
    private javax.swing.JLabel LABEL_NAMA_JUR;
    private javax.swing.JPanel MAIN_FRAME;
    // End of variables declaration//GEN-END:variables
}
