/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.manurul.view.modal;

import com.manurul.lib.InputBorder;
import com.manurul.lib.RoundedPanel;
import com.manurul.view.Dashboard;
import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author caesarhome
 */
public class konfirmasiBukuPengembalian extends javax.swing.JFrame {

    /**
     * Creates new form konfirmasiBukuPengembalian
     */
    private String status;
    
    public konfirmasiBukuPengembalian(String id_transaksi, String isbn, int row) {
        initComponents();
        
        // SET ICON
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../../src/LOGO_MANURUL.png")));

        // SET TITLE
        this.setTitle("MA Nurul Islam Library Management - Konfirmasi Pengembalian Buku");
        
        // SET PADDING
        InputBorder.set(INPUT_JUDUL, 8);
        InputBorder.set(INPUT_DENDA, 8);
        
        // GET DATA FROM DATABASE
        Dashboard.TM.getDetailBukuPengembalian(id_transaksi, isbn, row);
        
        // VISIBLE WHERE ON STATUS
        
        if(INPUT_STATUS.getSelectedItem().equals("Dipinjam")){
            INPUT_MASALAH.setEnabled(false);
            INPUT_DENDA.setEnabled(false);
            INPUT_BAYAR.setEnabled(false);
        }
        
        // set status
        status = INPUT_STATUS.getSelectedItem().toString();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CONTAINER = new RoundedPanel(15, Color.WHITE);
        BTN_KONFIRMASI = new javax.swing.JButton();
        LABEL_JUDUL = new javax.swing.JLabel();
        INPUT_JUDUL = new javax.swing.JTextField();
        LABEL_STATUS = new javax.swing.JLabel();
        LABEL_MASALAH = new javax.swing.JLabel();
        LABEL_DENDA = new javax.swing.JLabel();
        INPUT_STATUS = new javax.swing.JComboBox<>();
        INPUT_DENDA = new javax.swing.JTextField();
        INPUT_MASALAH = new javax.swing.JComboBox<>();
        INPUT_BAYAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BTN_KONFIRMASI.setBackground(new java.awt.Color(0, 171, 60));
        BTN_KONFIRMASI.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        BTN_KONFIRMASI.setForeground(new java.awt.Color(255, 255, 255));
        BTN_KONFIRMASI.setText("KONFIRMASI");
        BTN_KONFIRMASI.setBorder(null);

        LABEL_JUDUL.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_JUDUL.setText("Judul Buku");

        INPUT_JUDUL.setEditable(false);
        INPUT_JUDUL.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_JUDUL.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LABEL_STATUS.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_STATUS.setText("Status Buku");

        LABEL_MASALAH.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_MASALAH.setText("Detail Masalah");

        LABEL_DENDA.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_DENDA.setText("Sanksi / Denda");

        INPUT_STATUS.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_STATUS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dipinjam", "Bermasalah" }));
        INPUT_STATUS.setBorder(null);
        INPUT_STATUS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INPUT_STATUSActionPerformed(evt);
            }
        });

        INPUT_DENDA.setEditable(false);
        INPUT_DENDA.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_DENDA.setText("Rp.");
        INPUT_DENDA.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        INPUT_MASALAH.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_MASALAH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terlamat", "Hilang", "Rusak" }));
        INPUT_MASALAH.setBorder(null);

        INPUT_BAYAR.setBackground(new java.awt.Color(255, 102, 51));
        INPUT_BAYAR.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        INPUT_BAYAR.setForeground(new java.awt.Color(255, 255, 255));
        INPUT_BAYAR.setText("BAYAR");
        INPUT_BAYAR.setBorder(null);

        javax.swing.GroupLayout CONTAINERLayout = new javax.swing.GroupLayout(CONTAINER);
        CONTAINER.setLayout(CONTAINERLayout);
        CONTAINERLayout.setHorizontalGroup(
            CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CONTAINERLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(INPUT_STATUS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABEL_JUDUL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(INPUT_JUDUL, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_KONFIRMASI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABEL_STATUS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABEL_MASALAH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABEL_DENDA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(INPUT_MASALAH, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, CONTAINERLayout.createSequentialGroup()
                        .addComponent(INPUT_DENDA, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(INPUT_BAYAR, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)))
                .addGap(25, 25, 25))
        );
        CONTAINERLayout.setVerticalGroup(
            CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CONTAINERLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LABEL_JUDUL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_JUDUL, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LABEL_STATUS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_STATUS, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LABEL_MASALAH)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(INPUT_MASALAH, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LABEL_DENDA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(INPUT_DENDA, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(INPUT_BAYAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(BTN_KONFIRMASI, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(CONTAINER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(CONTAINER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(25, 25, 25))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void INPUT_STATUSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INPUT_STATUSActionPerformed

        INPUT_MASALAH.setEnabled(false);
        INPUT_DENDA.setEnabled(false);
        INPUT_BAYAR.setEnabled(false);
            
        if(INPUT_STATUS.getSelectedItem().equals("Bermasalah")){
            INPUT_MASALAH.setEnabled(true);
            INPUT_DENDA.setEnabled(true);
            INPUT_BAYAR.setEnabled(true);
        }
        
    }//GEN-LAST:event_INPUT_STATUSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(konfirmasiBukuPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(konfirmasiBukuPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(konfirmasiBukuPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(konfirmasiBukuPengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new konfirmasiBukuPengembalian("", "", 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_KONFIRMASI;
    private javax.swing.JPanel CONTAINER;
    private javax.swing.JButton INPUT_BAYAR;
    public static javax.swing.JTextField INPUT_DENDA;
    public static javax.swing.JTextField INPUT_JUDUL;
    public static javax.swing.JComboBox<String> INPUT_MASALAH;
    public static javax.swing.JComboBox<String> INPUT_STATUS;
    private javax.swing.JLabel LABEL_DENDA;
    private javax.swing.JLabel LABEL_JUDUL;
    private javax.swing.JLabel LABEL_MASALAH;
    private javax.swing.JLabel LABEL_STATUS;
    // End of variables declaration//GEN-END:variables
}
