/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.manurul.view.modal;

import com.manurul.lib.Characters;
import com.manurul.lib.InputBorder;
import com.manurul.lib.RoundedPanel;
import com.manurul.model.PenerbitModel;
import com.manurul.view.Dashboard;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author caesarhome
 */
public class PenerbitDATABUKU extends javax.swing.JFrame {

    /**
     * Creates new form PenerbitBuku
     */
    String title = "Edit";
    
    String action;
    String nama;
    String kontak;
    
    PenerbitModel PM = new PenerbitModel();
    ImageIcon successIcon;
    
    public PenerbitDATABUKU(String Action, String Nama) {
        initComponents();
        
        // SET VALUE STATE
        this.action = Action;
        this.nama = Nama;
        
        // SET SIZE
        this.setSize(1024, 345);
        
        // SET CENTER LOCATION
        this.setLocationRelativeTo(null);
        
        // SET DISABLE RESIZESABLE
        this.setResizable(false);
        
        // SET SUCCESS ICON
        ImageIcon successIcon = new ImageIcon(getClass().getResource("/com/manurul/src/ICON_SUCCESS.png"));
        this.successIcon = successIcon;
        
        // INIT INPUT BORDER PADDING
        InputBorder.set(INPUT_NAMA_PENERBIT, 8);
        InputBorder.set(INPUT_KONTAK, 8);
        InputBorder.set(INPUT_UPDATE, 8);
        InputBorder.set(INPUT_CREATED, 8);
        
        // SET COMPONENT BASED ON ACTION
        if(Action.equals("ADD")){
            
            this.title = "Tambah";
            
            this.setSize(1024, 285);
            
            LABEL_UPDATE.setVisible(false);
            INPUT_UPDATE.setVisible(false);
            
            LABEL_CREATED.setVisible(false);
            INPUT_CREATED.setVisible(false);
            
            BTN_HAPUS_PENERBIT.setVisible(false);
        
        }else{
            
            PM.getSelectedData(Nama);
            
            this.nama = PM.getNama();
            this.kontak = PM.getKontak();
            
            INPUT_NAMA_PENERBIT.setText(PM.getNama());
            INPUT_KONTAK.setText(PM.getKontak());
            INPUT_CREATED.setText(PM.getCreated());
            INPUT_UPDATE.setText(PM.getUpdated());
            
        }
        
        // SET TITLE
        this.setTitle("MA Nurul Islam Library Management - " + this.title + " Penerbit Buku");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MAIN_FRAME = new javax.swing.JPanel();
        CONTAINER = new RoundedPanel(15, Color.WHITE);
        INPUT_NAMA_PENERBIT = new javax.swing.JTextField();
        LABEL_NAMA_PENERBIT = new javax.swing.JLabel();
        LABEL_UPDATE = new javax.swing.JLabel();
        INPUT_UPDATE = new javax.swing.JTextField();
        INPUT_CREATED = new javax.swing.JTextField();
        LABEL_CREATED = new javax.swing.JLabel();
        INPUT_KONTAK = new javax.swing.JTextField();
        LABEL_KONTAK = new javax.swing.JLabel();
        BTN_HAPUS_PENERBIT = new javax.swing.JButton();
        BTN_SIMPAN_PENERBIT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);

        MAIN_FRAME.setBackground(new java.awt.Color(239, 240, 245));

        CONTAINER.setBackground(new java.awt.Color(239, 240, 245));

        INPUT_NAMA_PENERBIT.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_NAMA_PENERBIT.setForeground(new java.awt.Color(96, 96, 96));
        INPUT_NAMA_PENERBIT.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));

        LABEL_NAMA_PENERBIT.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_NAMA_PENERBIT.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_NAMA_PENERBIT.setText("Nama Penerbit");

        LABEL_UPDATE.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_UPDATE.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_UPDATE.setText("Terakhir Diperbarui");

        INPUT_UPDATE.setEditable(false);
        INPUT_UPDATE.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_UPDATE.setForeground(new java.awt.Color(96, 96, 96));
        INPUT_UPDATE.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));

        INPUT_CREATED.setEditable(false);
        INPUT_CREATED.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_CREATED.setForeground(new java.awt.Color(96, 96, 96));
        INPUT_CREATED.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));

        LABEL_CREATED.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_CREATED.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_CREATED.setText("Tanggal Dibuat");

        INPUT_KONTAK.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_KONTAK.setForeground(new java.awt.Color(96, 96, 96));
        INPUT_KONTAK.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));

        LABEL_KONTAK.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_KONTAK.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_KONTAK.setText("Kontak");

        javax.swing.GroupLayout CONTAINERLayout = new javax.swing.GroupLayout(CONTAINER);
        CONTAINER.setLayout(CONTAINERLayout);
        CONTAINERLayout.setHorizontalGroup(
            CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONTAINERLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(INPUT_CREATED, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LABEL_NAMA_PENERBIT, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addComponent(INPUT_NAMA_PENERBIT, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LABEL_CREATED, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(37, 37, 37)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_KONTAK, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CONTAINERLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LABEL_KONTAK, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LABEL_UPDATE, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(INPUT_UPDATE))
                .addGap(23, 23, 23))
        );
        CONTAINERLayout.setVerticalGroup(
            CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONTAINERLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LABEL_NAMA_PENERBIT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABEL_KONTAK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(INPUT_NAMA_PENERBIT)
                    .addComponent(INPUT_KONTAK, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CONTAINERLayout.createSequentialGroup()
                        .addComponent(LABEL_UPDATE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(INPUT_UPDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(CONTAINERLayout.createSequentialGroup()
                        .addComponent(LABEL_CREATED)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(INPUT_CREATED, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        BTN_HAPUS_PENERBIT.setBackground(new java.awt.Color(153, 153, 153));
        BTN_HAPUS_PENERBIT.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        BTN_HAPUS_PENERBIT.setForeground(new java.awt.Color(255, 255, 255));
        BTN_HAPUS_PENERBIT.setText("Hapus");
        BTN_HAPUS_PENERBIT.setBorder(null);
        BTN_HAPUS_PENERBIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_HAPUS_PENERBITMouseClicked(evt);
            }
        });

        BTN_SIMPAN_PENERBIT.setBackground(new java.awt.Color(0, 171, 60));
        BTN_SIMPAN_PENERBIT.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        BTN_SIMPAN_PENERBIT.setForeground(new java.awt.Color(255, 255, 255));
        BTN_SIMPAN_PENERBIT.setText("Simpan");
        BTN_SIMPAN_PENERBIT.setBorder(null);
        BTN_SIMPAN_PENERBIT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTN_SIMPAN_PENERBITMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MAIN_FRAMELayout = new javax.swing.GroupLayout(MAIN_FRAME);
        MAIN_FRAME.setLayout(MAIN_FRAMELayout);
        MAIN_FRAMELayout.setHorizontalGroup(
            MAIN_FRAMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MAIN_FRAMELayout.createSequentialGroup()
                .addGroup(MAIN_FRAMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MAIN_FRAMELayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(CONTAINER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MAIN_FRAMELayout.createSequentialGroup()
                        .addContainerGap(420, Short.MAX_VALUE)
                        .addComponent(BTN_HAPUS_PENERBIT, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_SIMPAN_PENERBIT, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        MAIN_FRAMELayout.setVerticalGroup(
            MAIN_FRAMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAIN_FRAMELayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(CONTAINER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(MAIN_FRAMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_SIMPAN_PENERBIT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_HAPUS_PENERBIT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_FRAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_FRAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean cekValidasi(){
        
        try{
            
            String nama = Characters.ucwords(INPUT_NAMA_PENERBIT.getText().replaceAll("[0-9]", "").trim());
            String kontak = INPUT_KONTAK.getText().replaceAll("[a-zA-Z]", "").trim();
            
            if(nama.equals("")){
                throw new Exception("Nilai nama harus terisi dan tidak berisi angka !");
            }
            
            if(kontak.equals("")){
                throw new Exception("Nilai kontak harus terisi dan berupa angka !");
            }
            
            System.out.println(kontak.length());
            if(kontak.length() >= 13){
                throw new Exception("Nilai kontak hanya memuat 13 angka !");
            }
            
            PM.setNama(nama);
            PM.setKontak(kontak);
        
            return true;
            
        }catch(Exception error){
        
            JOptionPane.showMessageDialog(null, error.getMessage(), "Terjadi Kesalahan!", JOptionPane.INFORMATION_MESSAGE);
            return false;
            
        }
    
    }
    
    private void inputRevalidate(){
        
        INPUT_NAMA_PENERBIT.setText(this.nama);
        INPUT_KONTAK.setText(this.kontak);
    
    }
    
    private void simpan(){
    
        if(cekValidasi()){
            if(PM.insertData()){
                JOptionPane.showMessageDialog(null, PM.getMessage(), "Sukses!", JOptionPane.INFORMATION_MESSAGE, this.successIcon);
                
                // refersh
                new PenerbitModel().getDataTable(Dashboard.SEARCH_PENERBIT.getText(), Dashboard.TAMPILKAN_PENERBIT.getSelectedItem().toString());
                
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, PM.getMessage(), "Terjadi Kesalahan!", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
    }
    
    private void update(){
    
        if(cekValidasi()){
            
            // cek perubahan
            if(!INPUT_NAMA_PENERBIT.getText().equals(this.nama) || !INPUT_KONTAK.getText().equals(this.kontak)){
                if(PM.updatedData()){
                    JOptionPane.showMessageDialog(null, PM.getMessage(), "Sukses!", JOptionPane.INFORMATION_MESSAGE, this.successIcon);

                    // refersh
                    new PenerbitModel().getDataTable(Dashboard.SEARCH_PENERBIT.getText(), Dashboard.TAMPILKAN_PENERBIT.getSelectedItem().toString());

                    this.dispose();
                }else{
                    inputRevalidate();
                    JOptionPane.showMessageDialog(null, PM.getMessage(), "Terjadi Kesalahan!", JOptionPane.INFORMATION_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Tidak ada perubahan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            
        }
        
    }
    
    private void delete(){
    
        inputRevalidate();
        
        int hapus = JOptionPane.showConfirmDialog(null, "Apakah anda ingin mengapus penerbit "+PM.getNama()+" ?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

        if(hapus == 0){
            if(PM.deleteData()){
                JOptionPane.showMessageDialog(null, PM.getMessage(), "Sukses!", JOptionPane.INFORMATION_MESSAGE, this.successIcon);

                // refersh
                new PenerbitModel().getDataTable(Dashboard.SEARCH_PENERBIT.getText(), Dashboard.TAMPILKAN_PENERBIT.getSelectedItem().toString());

                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, PM.getMessage(), "Terjadi Kesalahan!", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }
    
    private void BTN_SIMPAN_PENERBITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_SIMPAN_PENERBITMouseClicked
        if(this.action.equals("ADD")){
            simpan();
        }else{
            update();
        }
    }//GEN-LAST:event_BTN_SIMPAN_PENERBITMouseClicked

    private void BTN_HAPUS_PENERBITMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTN_HAPUS_PENERBITMouseClicked
        delete();
    }//GEN-LAST:event_BTN_HAPUS_PENERBITMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenerbitDATABUKU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenerbitDATABUKU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenerbitDATABUKU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenerbitDATABUKU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenerbitDATABUKU("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_HAPUS_PENERBIT;
    private javax.swing.JButton BTN_SIMPAN_PENERBIT;
    private javax.swing.JPanel CONTAINER;
    private javax.swing.JTextField INPUT_CREATED;
    private javax.swing.JTextField INPUT_KONTAK;
    private javax.swing.JTextField INPUT_NAMA_PENERBIT;
    private javax.swing.JTextField INPUT_UPDATE;
    private javax.swing.JLabel LABEL_CREATED;
    private javax.swing.JLabel LABEL_KONTAK;
    private javax.swing.JLabel LABEL_NAMA_PENERBIT;
    private javax.swing.JLabel LABEL_UPDATE;
    private javax.swing.JPanel MAIN_FRAME;
    // End of variables declaration//GEN-END:variables
}
