/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.manurul.view.modal;

import com.manurul.lib.InputBorder;
import java.awt.Toolkit;
import com.manurul.lib.RoundedPanel;
import java.awt.Color;

/**
 *
 * @author caesarhome
 */
public class PengurusUSER extends javax.swing.JFrame {

    /**
     * Creates new form JurusanUSER
     */
    String title = "Edit";
    
    public PengurusUSER(String Action, int ID) {
        initComponents();
        
        // SET SIZE
        this.setSize(1024, 450);
        
        // SET CENTER LOCATION
        this.setLocationRelativeTo(null);
        
        // SET DISABLE RESIZESABLE
        this.setResizable(false);
        
        // SET ICON
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../../src/LOGO_MANURUL.png")));
        
        // INIT INPUT BORDER PADDING
        InputBorder.set(INPUT_ID_PENGURUS, 8);
        InputBorder.set(INPUT_USERNAME, 8);
        InputBorder.set(INPUT_NIP, 8);
        InputBorder.set(INPUT_NAMA, 8);
        InputBorder.set(INPUT_PASSWORD, 8);
        InputBorder.set(INPUT_CREATED, 8);
        InputBorder.set(INPUT_UPDATED, 8);
        
        // SET COMPONENT BASED ON ACTION
        if(Action.equals("ADD")){
            
            this.title = "Tambah";
            
            LABEL_CREATED.setVisible(false);
            INPUT_CREATED.setVisible(false);
            LABEL_UPDATED.setVisible(false);
            INPUT_UPDATED.setVisible(false);
            BTN_HAPUS_JUR.setVisible(false);
            
        
        }
        
        // SET TITLE
        this.setTitle("MA Nurul Islam Library Management - " + this.title + " Pengurus");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MAIN_FRAME = new javax.swing.JPanel();
        CONTAINER = new RoundedPanel(15, Color.WHITE);
        INPUT_ID_PENGURUS = new javax.swing.JTextField();
        LABEL_ID_PENGURUS = new javax.swing.JLabel();
        INPUT_USERNAME = new javax.swing.JTextField();
        LABEL_USERNAME = new javax.swing.JLabel();
        LABEL_NIP = new javax.swing.JLabel();
        INPUT_NIP = new javax.swing.JTextField();
        LABEL_HAK_AKSES = new javax.swing.JLabel();
        LABEL_NAMA = new javax.swing.JLabel();
        INPUT_NAMA = new javax.swing.JTextField();
        LABEL_PASSWORD = new javax.swing.JLabel();
        INPUT_PASSWORD = new javax.swing.JTextField();
        LABEL_STATUS = new javax.swing.JLabel();
        INPUT_UPDATED = new javax.swing.JTextField();
        LABEL_UPDATED = new javax.swing.JLabel();
        LABEL_CREATED = new javax.swing.JLabel();
        INPUT_CREATED = new javax.swing.JTextField();
        COMBOBOX_STATUS = new javax.swing.JComboBox<>();
        COMBOBOX_HAK_AKSES = new javax.swing.JComboBox<>();
        BTN_HAPUS_JUR = new javax.swing.JButton();
        BTN_SIMPAN_JUR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setType(java.awt.Window.Type.POPUP);

        MAIN_FRAME.setBackground(new java.awt.Color(239, 240, 245));

        CONTAINER.setBackground(new java.awt.Color(239, 240, 245));

        INPUT_ID_PENGURUS.setEditable(false);
        INPUT_ID_PENGURUS.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_ID_PENGURUS.setForeground(new java.awt.Color(96, 96, 96));
        INPUT_ID_PENGURUS.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));

        LABEL_ID_PENGURUS.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_ID_PENGURUS.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_ID_PENGURUS.setText("ID Pengurus");

        INPUT_USERNAME.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_USERNAME.setForeground(new java.awt.Color(96, 96, 96));
        INPUT_USERNAME.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));
        INPUT_USERNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INPUT_USERNAMEActionPerformed(evt);
            }
        });

        LABEL_USERNAME.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_USERNAME.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_USERNAME.setText("Username");

        LABEL_NIP.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_NIP.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_NIP.setText("NIP");

        INPUT_NIP.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_NIP.setForeground(new java.awt.Color(96, 96, 96));
        INPUT_NIP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));

        LABEL_HAK_AKSES.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_HAK_AKSES.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_HAK_AKSES.setText("Hak Akses");

        LABEL_NAMA.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_NAMA.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_NAMA.setText("Nama Lengkap");

        INPUT_NAMA.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_NAMA.setForeground(new java.awt.Color(96, 96, 96));
        INPUT_NAMA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));

        LABEL_PASSWORD.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_PASSWORD.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_PASSWORD.setText("Password");

        INPUT_PASSWORD.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_PASSWORD.setForeground(new java.awt.Color(96, 96, 96));
        INPUT_PASSWORD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));
        INPUT_PASSWORD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INPUT_PASSWORDActionPerformed(evt);
            }
        });

        LABEL_STATUS.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_STATUS.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_STATUS.setText("Status");

        INPUT_UPDATED.setEditable(false);
        INPUT_UPDATED.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_UPDATED.setForeground(new java.awt.Color(96, 96, 96));
        INPUT_UPDATED.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));
        INPUT_UPDATED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INPUT_UPDATEDActionPerformed(evt);
            }
        });

        LABEL_UPDATED.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_UPDATED.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_UPDATED.setText("Terakhir Diperbarui");

        LABEL_CREATED.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        LABEL_CREATED.setForeground(new java.awt.Color(96, 96, 96));
        LABEL_CREATED.setText("Tanggal Dibuat");

        INPUT_CREATED.setEditable(false);
        INPUT_CREATED.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        INPUT_CREATED.setForeground(new java.awt.Color(96, 96, 96));
        INPUT_CREATED.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(96, 96, 96)));

        COMBOBOX_STATUS.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        COMBOBOX_STATUS.setForeground(new java.awt.Color(96, 96, 96));
        COMBOBOX_STATUS.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Blokir" }));

        COMBOBOX_HAK_AKSES.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        COMBOBOX_HAK_AKSES.setForeground(new java.awt.Color(96, 96, 96));
        COMBOBOX_HAK_AKSES.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administartor", "Staff" }));

        javax.swing.GroupLayout CONTAINERLayout = new javax.swing.GroupLayout(CONTAINER);
        CONTAINER.setLayout(CONTAINERLayout);
        CONTAINERLayout.setHorizontalGroup(
            CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONTAINERLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(INPUT_ID_PENGURUS, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LABEL_ID_PENGURUS, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(LABEL_NAMA, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(INPUT_NAMA, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LABEL_CREATED, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                    .addComponent(INPUT_CREATED, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(37, 37, 37)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_USERNAME)
                    .addComponent(LABEL_USERNAME, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(LABEL_PASSWORD, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(INPUT_PASSWORD)
                    .addComponent(LABEL_UPDATED, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(INPUT_UPDATED))
                .addGap(37, 37, 37)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(INPUT_NIP)
                    .addComponent(LABEL_NIP, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                    .addComponent(LABEL_HAK_AKSES, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABEL_STATUS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(COMBOBOX_STATUS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(COMBOBOX_HAK_AKSES, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );
        CONTAINERLayout.setVerticalGroup(
            CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CONTAINERLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABEL_ID_PENGURUS)
                    .addComponent(LABEL_USERNAME)
                    .addComponent(LABEL_NIP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INPUT_ID_PENGURUS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(INPUT_NIP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(INPUT_USERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LABEL_HAK_AKSES)
                    .addComponent(LABEL_NAMA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LABEL_PASSWORD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(INPUT_NAMA, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(INPUT_PASSWORD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(COMBOBOX_HAK_AKSES, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(CONTAINERLayout.createSequentialGroup()
                        .addComponent(LABEL_STATUS, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(COMBOBOX_STATUS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CONTAINERLayout.createSequentialGroup()
                        .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LABEL_UPDATED)
                            .addComponent(LABEL_CREATED, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(CONTAINERLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(INPUT_UPDATED, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(INPUT_CREATED, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25))
        );

        BTN_HAPUS_JUR.setBackground(new java.awt.Color(153, 153, 153));
        BTN_HAPUS_JUR.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        BTN_HAPUS_JUR.setForeground(new java.awt.Color(255, 255, 255));
        BTN_HAPUS_JUR.setText("Hapus");
        BTN_HAPUS_JUR.setBorder(null);

        BTN_SIMPAN_JUR.setBackground(new java.awt.Color(0, 171, 60));
        BTN_SIMPAN_JUR.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        BTN_SIMPAN_JUR.setForeground(new java.awt.Color(255, 255, 255));
        BTN_SIMPAN_JUR.setText("Simpan");
        BTN_SIMPAN_JUR.setBorder(null);

        javax.swing.GroupLayout MAIN_FRAMELayout = new javax.swing.GroupLayout(MAIN_FRAME);
        MAIN_FRAME.setLayout(MAIN_FRAMELayout);
        MAIN_FRAMELayout.setHorizontalGroup(
            MAIN_FRAMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MAIN_FRAMELayout.createSequentialGroup()
                .addGroup(MAIN_FRAMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MAIN_FRAMELayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(CONTAINER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MAIN_FRAMELayout.createSequentialGroup()
                        .addGap(420, 420, 420)
                        .addComponent(BTN_HAPUS_JUR, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN_SIMPAN_JUR, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        MAIN_FRAMELayout.setVerticalGroup(
            MAIN_FRAMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MAIN_FRAMELayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(CONTAINER, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(MAIN_FRAMELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_SIMPAN_JUR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_HAPUS_JUR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_FRAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MAIN_FRAME, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void INPUT_USERNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INPUT_USERNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INPUT_USERNAMEActionPerformed

    private void INPUT_UPDATEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INPUT_UPDATEDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INPUT_UPDATEDActionPerformed

    private void INPUT_PASSWORDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INPUT_PASSWORDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_INPUT_PASSWORDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PengurusUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PengurusUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PengurusUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PengurusUSER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PengurusUSER("", 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_HAPUS_JUR;
    private javax.swing.JButton BTN_SIMPAN_JUR;
    private javax.swing.JComboBox<String> COMBOBOX_HAK_AKSES;
    private javax.swing.JComboBox<String> COMBOBOX_STATUS;
    private javax.swing.JPanel CONTAINER;
    private javax.swing.JTextField INPUT_CREATED;
    private javax.swing.JTextField INPUT_ID_PENGURUS;
    private javax.swing.JTextField INPUT_NAMA;
    private javax.swing.JTextField INPUT_NIP;
    private javax.swing.JTextField INPUT_PASSWORD;
    private javax.swing.JTextField INPUT_UPDATED;
    private javax.swing.JTextField INPUT_USERNAME;
    private javax.swing.JLabel LABEL_CREATED;
    private javax.swing.JLabel LABEL_HAK_AKSES;
    private javax.swing.JLabel LABEL_ID_PENGURUS;
    private javax.swing.JLabel LABEL_NAMA;
    private javax.swing.JLabel LABEL_NIP;
    private javax.swing.JLabel LABEL_PASSWORD;
    private javax.swing.JLabel LABEL_STATUS;
    private javax.swing.JLabel LABEL_UPDATED;
    private javax.swing.JLabel LABEL_USERNAME;
    private javax.swing.JPanel MAIN_FRAME;
    // End of variables declaration//GEN-END:variables
}
